import { DataTypes } from "sequelize";
const ID = { type: DataTypes.BIGINT.UNSIGNED, autoIncrement: true, primaryKey: true }; const TENANT = { type: DataTypes.BIGINT.UNSIGNED, allowNull: false };
export async function up(q) {
  await q.createTable("package", { id: ID, tenant_id: TENANT, name: { type: DataTypes.STRING(160), allowNull: false }, slug: { type: DataTypes.STRING(100), allowNull: false }, description: DataTypes.TEXT, duration_value: { type: DataTypes.INTEGER.UNSIGNED, allowNull: false, defaultValue: 1 }, duration_unit: { type: DataTypes.ENUM("one_time", "month"), allowNull: false }, price: { type: DataTypes.DECIMAL(12, 2), allowNull: false }, currency: { type: DataTypes.STRING(8), allowNull: false, defaultValue: "EGP" }, active: { type: DataTypes.BOOLEAN, allowNull: false, defaultValue: true }, sort_order: { type: DataTypes.INTEGER, allowNull: false, defaultValue: 0 }, created_at: DataTypes.DATE, updated_at: DataTypes.DATE });
  await q.createTable("package_entitlement", { id: ID, tenant_id: TENANT, package_id: { type: DataTypes.BIGINT.UNSIGNED, allowNull: false }, code: { type: DataTypes.STRING(80), allowNull: false }, allowed: { type: DataTypes.BOOLEAN, allowNull: false, defaultValue: true }, limit_value: DataTypes.INTEGER.UNSIGNED, period_unit: DataTypes.STRING(20), config_json: DataTypes.JSON, created_at: DataTypes.DATE, updated_at: DataTypes.DATE });
  await q.createTable("subscription", { id: ID, tenant_id: TENANT, patient_id: { type: DataTypes.BIGINT.UNSIGNED, allowNull: false }, package_id: { type: DataTypes.BIGINT.UNSIGNED, allowNull: false }, status: { type: DataTypes.ENUM("pending", "active", "expired", "cancelled", "rejected"), allowNull: false, defaultValue: "pending" }, starts_at: DataTypes.DATE, ends_at: DataTypes.DATE, approved_at: DataTypes.DATE, created_at: DataTypes.DATE, updated_at: DataTypes.DATE });
  await q.createTable("subscription_entitlement", { id: ID, tenant_id: TENANT, subscription_id: { type: DataTypes.BIGINT.UNSIGNED, allowNull: false }, package_entitlement_id: { type: DataTypes.BIGINT.UNSIGNED, allowNull: false }, code: { type: DataTypes.STRING(80), allowNull: false }, allowed: { type: DataTypes.BOOLEAN, allowNull: false }, limit_value: DataTypes.INTEGER.UNSIGNED, used_value: { type: DataTypes.INTEGER.UNSIGNED, allowNull: false, defaultValue: 0 }, created_at: DataTypes.DATE, updated_at: DataTypes.DATE });
  await q.createTable("payment", { id: ID, tenant_id: TENANT, patient_id: { type: DataTypes.BIGINT.UNSIGNED, allowNull: false }, package_id: { type: DataTypes.BIGINT.UNSIGNED, allowNull: false }, subscription_id: { type: DataTypes.BIGINT.UNSIGNED, allowNull: true }, amount: { type: DataTypes.DECIMAL(12, 2), allowNull: false }, currency: { type: DataTypes.STRING(8), allowNull: false }, method: { type: DataTypes.ENUM("vodafone_cash", "instapay"), allowNull: false }, sender_phone: { type: DataTypes.STRING(20), allowNull: false }, transaction_reference: DataTypes.STRING(120), submitted_at: { type: DataTypes.DATE, allowNull: false }, reviewed_at: DataTypes.DATE, reviewed_by: DataTypes.BIGINT.UNSIGNED, rejection_reason: DataTypes.TEXT, status: { type: DataTypes.ENUM("pending", "approved", "rejected"), allowNull: false, defaultValue: "pending" }, created_at: DataTypes.DATE, updated_at: DataTypes.DATE });
  await q.createTable("payment_receipt", { id: ID, tenant_id: TENANT, payment_id: { type: DataTypes.BIGINT.UNSIGNED, allowNull: false }, storage_key: { type: DataTypes.STRING(255), allowNull: false }, original_name: { type: DataTypes.STRING(190), allowNull: false }, mime_type: { type: DataTypes.STRING(80), allowNull: false }, size_bytes: { type: DataTypes.INTEGER.UNSIGNED, allowNull: false }, created_at: DataTypes.DATE, updated_at: DataTypes.DATE });
  await q.createTable("payment_review", { id: ID, tenant_id: TENANT, payment_id: { type: DataTypes.BIGINT.UNSIGNED, allowNull: false }, status: { type: DataTypes.ENUM("approved", "rejected"), allowNull: false }, reviewed_by: { type: DataTypes.BIGINT.UNSIGNED, allowNull: false }, reason: DataTypes.TEXT, created_at: DataTypes.DATE, updated_at: DataTypes.DATE });
  for (const t of ["package", "package_entitlement", "subscription", "subscription_entitlement", "payment", "payment_receipt", "payment_review"]) await q.addIndex(t, ["tenant_id"], { name: `${t}_tenant` });
  const [tenants] = await q.sequelize.query("SELECT id FROM tenant WHERE is_default = 1 LIMIT 1"); const tenantId = tenants[0]?.id;
  if (tenantId) {
    await q.bulkInsert("package", [
      { tenant_id: tenantId, name: "Consultation", slug: "consultation", description: "One-time doctor consultation", duration_value: 1, duration_unit: "one_time", price: 0, currency: "EGP", active: true, sort_order: 1, created_at: new Date(), updated_at: new Date() },
      { tenant_id: tenantId, name: "Monthly Care", slug: "monthly-care", description: "One month of coordinated care", duration_value: 1, duration_unit: "month", price: 0, currency: "EGP", active: true, sort_order: 2, created_at: new Date(), updated_at: new Date() },
      { tenant_id: tenantId, name: "3-Month Care", slug: "three-month-care", description: "Three months of coordinated care", duration_value: 3, duration_unit: "month", price: 0, currency: "EGP", active: true, sort_order: 3, created_at: new Date(), updated_at: new Date() },
    ]);
    const [packages] = await q.sequelize.query("SELECT id, slug FROM package WHERE tenant_id = :tenantId", { replacements: { tenantId } }); const bySlug = Object.fromEntries(packages.map((p) => [p.slug, p.id])); const now = new Date();
    await q.bulkInsert("package_entitlement", ["nutrition_plan", "exercise_plan", "weekly_checkin", "live_session", "doctor_followup"].flatMap((code) => ["monthly-care", "three-month-care"].map((slug) => ({ tenant_id: tenantId, package_id: bySlug[slug], code, allowed: true, created_at: now, updated_at: now }))).concat([{ tenant_id: tenantId, package_id: bySlug.consultation, code: "consultation", allowed: true, created_at: now, updated_at: now }]));
  }
}
