import { useEffect, useState } from "react";
import DashboardShell from "../shared/DashboardShell";
import NotificationsPanel from "../shared/NotificationsPanel";
import PaymentReview from "./PaymentReview";
import AdminConfiguration from "./AdminConfiguration";
import { reviewApi, appointmentApi } from "../../api/client";
import { useAuth } from "../../context/AuthProvider";
function Empty({text}){return <div className="empty-state">{text}</div>}
function Reviews({rows,reload}){const [busy,setBusy]=useState(null);const action=async(id,fn)=>{setBusy(id);try{await fn();await reload();}finally{setBusy(null);}};return <><div className="page-heading"><h2>Doctor review queue</h2><p className="muted">Review and approve submitted assessments.</p></div><section className="panel table-wrap"><table><thead><tr><th>Patient</th><th>Submitted</th><th>Priority</th><th>Status</th><th>Actions</th></tr></thead><tbody>{rows.map(r=><tr key={r.id}><td>{r.patientName||r.referenceNumber}</td><td>{r.submittedAt?new Date(r.submittedAt).toLocaleDateString():"—"}</td><td>{r.priority}</td><td>{r.status}</td><td className="row-actions">{r.status==="queued"&&<button disabled={busy===r.id} onClick={()=>action(r.id,()=>reviewApi.assign(r.id,{}))}>Assign</button>}{r.status==="assigned"&&<button onClick={()=>action(r.id,()=>reviewApi.open(r.id))}>Open</button>}{r.status==="in_review"&&<><button onClick={()=>action(r.id,()=>reviewApi.approve(r.id,{}))}>Approve</button><button onClick={()=>action(r.id,()=>reviewApi.reject(r.id,{reason:"Needs clinical follow-up"}))}>Reject</button></>}</td></tr>)}</tbody></table>{!rows.length&&<Empty text="No reviews in the queue."/>}</section></>}
function Appointments({rows,reload}){return <><div className="page-heading"><h2>Appointments</h2></div><section className="panel table-wrap"><table><thead><tr><th>Patient</th><th>Start</th><th>Type</th><th>Status</th><th>Actions</th></tr></thead><tbody>{rows.map(a=><tr key={a.id}><td>{a.patient_id||a.patientId}</td><td>{a.scheduled_start_at?new Date(a.scheduled_start_at).toLocaleString():"—"}</td><td>{a.type}</td><td>{a.status}</td><td>{a.status==="pending"&&<button onClick={async()=>{await appointmentApi.transition(a.id,"confirm");reload();}}>Confirm</button>}{a.status==="confirmed"&&<button onClick={async()=>{await appointmentApi.transition(a.id,"complete");reload();}}>Complete</button>}</td></tr>)}</tbody></table>{!rows.length&&<Empty text="No appointments found."/>}</section></>}
export default function DoctorDashboard({path}){const {user}=useAuth();const [reviews,setReviews]=useState([]);const [appointments,setAppointments]=useState([]);const reload=async()=>{const [r,a]=await Promise.all([reviewApi.list(),user.doctorId?appointmentApi.doctorList(user.doctorId):Promise.resolve([])]);setReviews(r||[]);setAppointments(a||[]);};useEffect(()=>{reload().catch(()=>{});},[user.doctorId]);const page=path==="/doctor/payments"?<PaymentReview/>:path==="/doctor/configuration"?<AdminConfiguration/>:path==="/doctor/notifications"?<NotificationsPanel/>:path==="/doctor/reviews"?<Reviews rows={reviews} reload={reload}/>:path==="/doctor/appointments"?<Appointments rows={appointments} reload={reload}/>:<><div className="page-heading"><span className="eyebrow">CLINICAL WORKSPACE</span><h2>Doctor workspace</h2></div><div className="metric-grid"><section className="metric-card"><span className="muted">Pending reviews</span><strong>{reviews.length}</strong></section><section className="metric-card"><span className="muted">Appointments</span><strong>{appointments.length}</strong></section></div><NotificationsPanel compact/></>;return <DashboardShell title="Doctor workspace" nav={[{path:"/doctor",label:"Overview",icon:"⌂"},{path:"/doctor/reviews",label:"Review queue",icon:"◈"},{path:"/doctor/payments",label:"Payment review",icon:"¤"},{path:"/doctor/configuration",label:"Configuration",icon:"⚙"},{path:"/doctor/appointments",label:"Appointments",icon:"◷"},{path:"/doctor/notifications",label:"Notifications",icon:"●"}]}>{page}</DashboardShell>}
