import { DataTypes } from "sequelize";
import { sequelize } from "../config/database.js";

const ID = { type: DataTypes.BIGINT.UNSIGNED, autoIncrement: true, primaryKey: true };
const tenant = { type: DataTypes.BIGINT.UNSIGNED, allowNull: false };
export const Package = sequelize.define("package", { id: ID, tenant_id: tenant, name: { type: DataTypes.STRING(160), allowNull: false }, slug: { type: DataTypes.STRING(100), allowNull: false }, description: DataTypes.TEXT, duration_value: { type: DataTypes.INTEGER.UNSIGNED, allowNull: false, defaultValue: 1 }, duration_unit: { type: DataTypes.ENUM("one_time", "month"), allowNull: false }, price: { type: DataTypes.DECIMAL(12, 2), allowNull: false }, currency: { type: DataTypes.STRING(8), allowNull: false, defaultValue: "EGP" }, active: { type: DataTypes.BOOLEAN, allowNull: false, defaultValue: true }, sort_order: { type: DataTypes.INTEGER, allowNull: false, defaultValue: 0 } }, { tableName: "package", underscored: true });
export const PackageEntitlement = sequelize.define("package_entitlement", { id: ID, tenant_id: tenant, package_id: { type: DataTypes.BIGINT.UNSIGNED, allowNull: false }, code: { type: DataTypes.STRING(80), allowNull: false }, allowed: { type: DataTypes.BOOLEAN, allowNull: false, defaultValue: true }, limit_value: DataTypes.INTEGER.UNSIGNED, period_unit: DataTypes.STRING(20), config_json: DataTypes.JSON }, { tableName: "package_entitlement", underscored: true });
export const Subscription = sequelize.define("subscription", { id: ID, tenant_id: tenant, patient_id: { type: DataTypes.BIGINT.UNSIGNED, allowNull: false }, package_id: { type: DataTypes.BIGINT.UNSIGNED, allowNull: false }, status: { type: DataTypes.ENUM("pending", "active", "expired", "cancelled", "rejected"), allowNull: false, defaultValue: "pending" }, starts_at: DataTypes.DATE, ends_at: DataTypes.DATE, approved_at: DataTypes.DATE }, { tableName: "subscription", underscored: true });
export const SubscriptionEntitlement = sequelize.define("subscription_entitlement", { id: ID, tenant_id: tenant, subscription_id: { type: DataTypes.BIGINT.UNSIGNED, allowNull: false }, package_entitlement_id: { type: DataTypes.BIGINT.UNSIGNED, allowNull: false }, code: { type: DataTypes.STRING(80), allowNull: false }, allowed: { type: DataTypes.BOOLEAN, allowNull: false }, limit_value: DataTypes.INTEGER.UNSIGNED, used_value: { type: DataTypes.INTEGER.UNSIGNED, allowNull: false, defaultValue: 0 } }, { tableName: "subscription_entitlement", underscored: true });
export const Payment = sequelize.define("payment", { id: ID, tenant_id: tenant, patient_id: { type: DataTypes.BIGINT.UNSIGNED, allowNull: false }, package_id: { type: DataTypes.BIGINT.UNSIGNED, allowNull: false }, subscription_id: { type: DataTypes.BIGINT.UNSIGNED, allowNull: true }, amount: { type: DataTypes.DECIMAL(12, 2), allowNull: false }, currency: { type: DataTypes.STRING(8), allowNull: false }, method: { type: DataTypes.ENUM("vodafone_cash", "instapay"), allowNull: false }, sender_phone: { type: DataTypes.STRING(20), allowNull: false }, transaction_reference: DataTypes.STRING(120), upgrade_json: DataTypes.JSON, submitted_at: { type: DataTypes.DATE, allowNull: false, defaultValue: DataTypes.NOW }, reviewed_at: DataTypes.DATE, reviewed_by: DataTypes.BIGINT.UNSIGNED, rejection_reason: DataTypes.TEXT, status: { type: DataTypes.ENUM("pending", "approved", "rejected"), allowNull: false, defaultValue: "pending" } }, { tableName: "payment", underscored: true });
export const PaymentReceipt = sequelize.define("payment_receipt", { id: ID, tenant_id: tenant, payment_id: { type: DataTypes.BIGINT.UNSIGNED, allowNull: false }, storage_key: { type: DataTypes.STRING(255), allowNull: false }, original_name: { type: DataTypes.STRING(190), allowNull: false }, mime_type: { type: DataTypes.STRING(80), allowNull: false }, size_bytes: { type: DataTypes.INTEGER.UNSIGNED, allowNull: false } }, { tableName: "payment_receipt", underscored: true });
export const PaymentReview = sequelize.define("payment_review", { id: ID, tenant_id: tenant, payment_id: { type: DataTypes.BIGINT.UNSIGNED, allowNull: false }, status: { type: DataTypes.ENUM("approved", "rejected"), allowNull: false }, reviewed_by: { type: DataTypes.BIGINT.UNSIGNED, allowNull: false }, reason: DataTypes.TEXT }, { tableName: "payment_review", underscored: true });
export const GROUP_16 = { Package, PackageEntitlement, Subscription, SubscriptionEntitlement, Payment, PaymentReceipt, PaymentReview };
