import { useEffect, useState } from "react";
import { paymentApi } from "../../api/client";

function fileData(file) { return new Promise((resolve, reject) => { const reader = new FileReader(); reader.onload = () => resolve(reader.result); reader.onerror = reject; reader.readAsDataURL(file); }); }
export default function PaymentCenter() {
  const [packages, setPackages] = useState([]); const [settings, setSettings] = useState(null); const [payments, setPayments] = useState([]); const [selected, setSelected] = useState(null); const [busy, setBusy] = useState(false); const [message, setMessage] = useState("");
  const load = async () => { const [p, s, h] = await Promise.all([paymentApi.packages(), paymentApi.settings(), paymentApi.list()]); setPackages(p || []); setSettings(s); setPayments(h || []); };
  useEffect(() => { load().catch((e) => setMessage(e.message)); }, []);
  const submit = async (event) => { event.preventDefault(); setBusy(true); setMessage(""); try { const form = new FormData(event.currentTarget); const payment = await paymentApi.create({ packageId: selected.id, method: form.get("method"), senderPhone: form.get("senderPhone"), transactionReference: form.get("transactionReference") || undefined }); const file = form.get("receipt"); if (file?.size) await paymentApi.receipt(payment.id, { mimeType: file.type, originalName: file.name, data: await fileData(file) }); setMessage("Payment submitted and awaiting review."); setSelected(null); await load(); event.currentTarget.reset(); } catch (e) { setMessage(e.message); } finally { setBusy(false); } };
  return <><div className="page-heading"><h2>Packages & payments</h2><p className="muted">The server determines the price and currency. Transfer manually, then submit proof for review.</p></div>{message && <p className="form-error">{message}</p>}<div className="metric-grid">{packages.map((pkg) => <section className="metric-card" key={pkg.id}><span className="muted">{pkg.name}</span><strong>{pkg.price} {pkg.currency}</strong><small>{pkg.description}</small><button className="primary-button" onClick={() => setSelected(pkg)}>Choose package</button></section>)}</div>{selected && <section className="panel"><div className="panel-title"><h3>Manual payment: {selected.name} — {selected.price} {selected.currency}</h3><button className="text-button" onClick={() => setSelected(null)}>Cancel</button></div><p className="muted">Vodafone Cash: {settings?.vodafone_cash?.enabled ? settings.vodafone_cash.destination || "Destination not configured" : "Unavailable"}</p><p className="muted">InstaPay: {settings?.instapay?.enabled ? settings.instapay.destination || "Destination not configured" : "Unavailable"}</p><p className="muted">{settings?.instructions?.en}</p><form className="checkin-form" onSubmit={submit}><label>Payment method<select name="method" required><option value="vodafone_cash" disabled={!settings?.vodafone_cash?.enabled}>Vodafone Cash</option><option value="instapay" disabled={!settings?.instapay?.enabled}>InstaPay</option></select></label><label>Sender phone<input name="senderPhone" required inputMode="tel" /></label><label>Transaction reference (optional)<input name="transactionReference" /></label><label>Receipt image/PDF<input name="receipt" type="file" accept="image/png,image/jpeg,application/pdf" required /></label><button className="primary-button" disabled={busy}>{busy ? "Submitting…" : "Submit payment"}</button></form></section>}<section className="panel"><div className="panel-title"><h3>Payment history</h3><span className="muted">{payments.length} submissions</span></div>{payments.map((p) => <div className="list-row" key={p.id}><span><strong>{p.package?.name || `Payment #${p.id}`}</strong><small className="muted">{p.method} · {p.amount} {p.currency}</small></span><span className={`status status-${p.status}`}>{p.status}</span></div>)}{!payments.length && <p className="muted">No payments submitted.</p>}</section></>;
}
