import { sequelize, models } from "../models/index.js";
import { AppError } from "../utils/errors.js";
import { auditService } from "./audit.service.js";
const { Package, PackageEntitlement, PlatformSetting } = models;
function admin(auth) { if (!auth) throw new AppError(401, "AUTH_REQUIRED", "Authentication required"); if (auth.membership.role !== "doctor") throw new AppError(403, "CONFIG_WRITE_FORBIDDEN", "Only authorized doctors may modify configuration"); return String(auth.user.id); }
export const configurationService = {
  async packages({ tenantId }) { return Package.findAll({ where: { tenant_id: tenantId }, include: [{ model: PackageEntitlement, required: false }], order: [["sort_order", "ASC"]] }); },
  async updatePackage({ tenantId, auth, id, body, ip }) { const actor = admin(auth); return sequelize.transaction(async (t) => { const row = await Package.findOne({ where: { id, tenant_id: tenantId }, transaction: t, lock: t.LOCK.UPDATE }); if (!row) throw new AppError(404, "PACKAGE_NOT_FOUND", "Package not found"); if (body.price !== undefined && (!Number.isFinite(Number(body.price)) || Number(body.price) < 0)) throw new AppError(422, "CONFIG_VALIDATION_ERROR", "Price must be a non-negative number"); const old = { price: String(row.price), active: row.active }; for (const [key, column] of Object.entries({ name: "name", description: "description", durationValue: "duration_value", durationUnit: "duration_unit", price: "price", currency: "currency", active: "active", sortOrder: "sort_order" })) if (body[key] !== undefined) row[column] = body[key]; await row.save({ transaction: t }); if (Array.isArray(body.entitlements)) for (const ent of body.entitlements) { if (!ent.code) throw new AppError(422, "CONFIG_VALIDATION_ERROR", "Entitlement code is required"); const [item] = await PackageEntitlement.findOrCreate({ where: { package_id: row.id, tenant_id: tenantId, code: ent.code }, defaults: { allowed: Boolean(ent.allowed), limit_value: ent.limitValue ?? null, period_unit: ent.periodUnit || null }, transaction: t }); item.allowed = Boolean(ent.allowed); item.limit_value = ent.limitValue ?? null; item.period_unit = ent.periodUnit || null; await item.save({ transaction: t }); } await auditService.record({ tenantId, action: "configuration.package_updated", entity: "package", entityRef: String(row.id), metadata: { old, new: { price: String(row.price), active: row.active } }, actorType: "doctor", actorId: actor, ip, transaction: t }); return row.toJSON(); }); },
  async updateSettings({ tenantId, auth, body, ip }) { const actor = admin(auth); const updates = { "payment.vodafone_cash.enabled": body.vodafoneCash?.enabled, "payment.vodafone_cash.destination": body.vodafoneCash?.destination, "payment.instapay.enabled": body.instapay?.enabled, "payment.instapay.destination": body.instapay?.destination, "payment.instructions.ar": body.instructions?.ar, "payment.instructions.en": body.instructions?.en }; return sequelize.transaction(async (t) => { for (const [key, value] of Object.entries(updates)) { if (value === undefined) continue; const [row, created] = await PlatformSetting.findOrCreate({ where: { tenant_id: tenantId, key }, defaults: { tenant_id: tenantId, key, value: String(value), value_type: typeof value === "boolean" ? "boolean" : "string" }, transaction: t }); if (!created) { const old = row.value; row.value = String(value); await row.save({ transaction: t }); await auditService.record({ tenantId, action: "configuration.payment_setting_updated", entity: "platform_setting", entityRef: key, metadata: { oldPresent: Boolean(old), newPresent: Boolean(row.value) }, actorType: "doctor", actorId: actor, ip, transaction: t }); } } return { updated: true }; }); },
};
