import { models } from "../models/index.js";
import { AppError } from "../utils/errors.js";
const { Notification, NotificationPreference, AuthUser, AuthUserTenant } = models;
const CATALOG = { assessment_submitted: ["Assessment submitted", "A new assessment is ready for review."], review_queued: ["Review queued", "A clinical review is waiting."], review_approved: ["Review approved", "Your review has been approved."], review_rejected: ["Review rejected", "Your review requires follow-up."], review_needs_clarification: ["Clarification requested", "Additional clarification is required."], payment_submitted: ["Payment submitted", "Your manual payment is awaiting review."], payment_approved: ["Payment approved", "Your access has been activated."], payment_rejected: ["Payment rejected", "Your payment needs attention."], appointment_confirmed: ["Appointment confirmed", "Your appointment is confirmed."], appointment_cancelled: ["Appointment cancelled", "An appointment was cancelled."], appointment_completed: ["Appointment completed", "An appointment was completed."], appointment_booked: ["New booking", "A patient booked an appointment."], nutrition_plan_activated: ["Nutrition plan active", "Your nutrition plan is now active."], exercise_plan_activated: ["Exercise plan active", "Your exercise plan is now active."], plan_version_updated: ["Plan updated", "A plan version was updated."], live_session_ready: ["Live session ready", "A live session is ready."], live_session_failed: ["Live session unavailable", "A live session could not be prepared."] };
export const notificationService = {
  async emit({ tenantId, recipientUserId, recipientRole, type, relatedEntity, relatedRef, locale = "en", transaction }) { const item = CATALOG[type]; if (!item) throw new AppError(422, "NOTIFICATION_TYPE_INVALID", "Unknown notification type"); const existing = await Notification.findOne({ where: { tenant_id: tenantId, recipient_user_id: recipientUserId, type, related_ref: relatedRef || null }, transaction }); if (existing) return existing.toJSON(); const pref = await NotificationPreference.findOne({ where: { tenant_id: tenantId, recipient_user_id: recipientUserId, notification_type: type, channel: "in_app" }, transaction }); if (pref?.enabled === false) return null; return (await Notification.create({ tenant_id: tenantId, recipient_user_id: recipientUserId, recipient_role: recipientRole, type, title: item[0], message: item[1], locale, related_entity: relatedEntity || null, related_ref: relatedRef || null }, { transaction })).toJSON(); },
  async list({ tenantId, auth, unreadOnly = false }) { if (!auth) throw new AppError(401, "AUTH_REQUIRED", "Authentication required"); return Notification.findAll({ where: { tenant_id: tenantId, recipient_user_id: auth.user.id, ...(unreadOnly ? { read_at: null } : {}) }, order: [["created_at", "DESC"]], raw: true }); },
  async read({ tenantId, auth, id }) { const row = await Notification.findOne({ where: { id, tenant_id: tenantId, recipient_user_id: auth.user.id } }); if (!row) throw new AppError(404, "NOTIFICATION_NOT_FOUND", "Notification not found"); row.read_at = new Date(); await row.save(); return row.toJSON(); },
  async readAll({ tenantId, auth }) { await Notification.update({ read_at: new Date() }, { where: { tenant_id: tenantId, recipient_user_id: auth.user.id, read_at: null } }); return { markedRead: true }; },
  async preferences({ tenantId, auth }) { return NotificationPreference.findAll({ where: { tenant_id: tenantId, recipient_user_id: auth.user.id }, raw: true }); },
  async setPreference({ tenantId, auth, body }) { const allowed = ["in_app", "email", "whatsapp", "sms"]; if (!allowed.includes(body.channel)) throw new AppError(422, "NOTIFICATION_CHANNEL_INVALID", "Unsupported notification channel"); const [row] = await NotificationPreference.findOrCreate({ where: { tenant_id: tenantId, recipient_user_id: auth.user.id, notification_type: body.notificationType, channel: body.channel }, defaults: { enabled: Boolean(body.enabled) } }); if (row.enabled !== Boolean(body.enabled)) { row.enabled = Boolean(body.enabled); await row.save(); } return row.toJSON(); },
  async usersForRole({ tenantId, role }) { return AuthUser.findAll({ include: [{ model: AuthUserTenant, where: { tenant_id: tenantId, role, active: true }, required: true }], where: { status: "enabled" }, raw: true }); },
  async emitForPatient({ tenantId, patientId, type, relatedEntity, relatedRef, transaction }) { const user = await AuthUser.findOne({ include: [{ model: AuthUserTenant, where: { tenant_id: tenantId, role: "patient", active: true }, required: true }], where: { patient_id: patientId, status: "enabled" }, transaction, raw: true }); return user ? this.emit({ tenantId, recipientUserId: user.id, recipientRole: "patient", type, relatedEntity, relatedRef, transaction }) : null; },
  async emitForDoctor({ tenantId, doctorId, type, relatedEntity, relatedRef, transaction }) { const user = await AuthUser.findOne({ include: [{ model: AuthUserTenant, where: { tenant_id: tenantId, role: "doctor", active: true }, required: true }], where: { doctor_id: doctorId, status: "enabled" }, transaction, raw: true }); return user ? this.emit({ tenantId, recipientUserId: user.id, recipientRole: "doctor", type, relatedEntity, relatedRef, transaction }) : null; },
};
