import { describe, it, before, after } from "node:test";
import assert from "node:assert/strict";
import { createApp } from "../../src/app.js";
import { sequelize } from "../../src/config/database.js";
import { models } from "../../src/models/index.js";
import { hashPassword } from "../../src/utils/auth-crypto.js";
const { Tenant, Doctor, Patient, AuthUser, AuthUserTenant, Package, PlatformSetting } = models;
let server; let base; let available = false; let tenant; let patient; let other; let doctor; let patientUser; let otherUser; let doctorUser;
async function request(path, options = {}) { return fetch(`${base}${path}`, { ...options, headers: { "Content-Type": "application/json", ...(options.headers || {}) } }); }
async function login(user, password) { const r = await request("/api/v1/auth/login", { method: "POST", body: JSON.stringify({ identifier: user.email, password, tenantSlug: tenant.slug }) }); return (await r.json()).data.accessToken; }
function h(token) { return { Authorization: `Bearer ${token}`, "X-Tenant-Slug": tenant.slug }; }
before(async () => { try { await sequelize.authenticate(); available = true; } catch { return; } tenant = await Tenant.findOne({ where: { slug: "dr-kareem" } }); doctor = await Doctor.findOne({ where: { tenant_id: tenant.id, active: true } }); patient = await Patient.create({ tenant_id: tenant.id, full_name: "Payment Patient", status: "active" }); other = await Patient.create({ tenant_id: tenant.id, full_name: "Other Payment Patient", status: "active" }); patientUser = await AuthUser.create({ email: `payment-p-${Date.now()}@test.local`, password_hash: await hashPassword("Payment1234!"), user_type: "patient", patient_id: patient.id, status: "enabled" }); otherUser = await AuthUser.create({ email: `payment-o-${Date.now()}@test.local`, password_hash: await hashPassword("Payment1234!"), user_type: "patient", patient_id: other.id, status: "enabled" }); doctorUser = await AuthUser.create({ email: `payment-d-${Date.now()}@test.local`, password_hash: await hashPassword("Payment1234!"), user_type: "doctor", doctor_id: doctor.id, status: "enabled" }); await AuthUserTenant.bulkCreate([{ user_id: patientUser.id, tenant_id: tenant.id, role: "patient", active: true }, { user_id: otherUser.id, tenant_id: tenant.id, role: "patient", active: true }, { user_id: doctorUser.id, tenant_id: tenant.id, role: "doctor", active: true }]); server = createApp().listen(0); base = `http://localhost:${server.address().port}`; });
after(async () => { if (server) await new Promise((resolve) => server.close(resolve)); await sequelize.close(); });
describe("Phase 4 manual payments", { concurrency: false }, () => {
  before(async () => { if (!available) return; await Package.update({ price: "1250.00", active: true }, { where: { tenant_id: tenant.id, slug: "monthly-care" } }); await PlatformSetting.update({ value: "01000000000" }, { where: { key: "payment.vodafone_cash.destination" } }); await PlatformSetting.update({ value: "test@instapay" }, { where: { key: "payment.instapay.destination" } }); });
  it("lists packages and keeps amount server-resolved", async (t) => { if (!available) return t.skip(); const token = await login(patientUser, "Payment1234!"); const listed = await request("/api/v1/packages", { headers: h(token) }); assert.equal(listed.status, 200); const pack = (await listed.json()).data.find((x) => x.slug === "monthly-care"); assert.ok(pack); const payment = await request("/api/v1/payments", { method: "POST", headers: h(token), body: JSON.stringify({ packageId: pack.id, method: "vodafone_cash", senderPhone: "01012345678", amount: "999999" }) }); const body = await payment.json(); assert.equal(payment.status, 201); assert.equal(String(body.data.amount), String(pack.price)); });
  it("supports receipt upload, private ownership, rejection, and approval idempotency", async (t) => { if (!available) return t.skip(); const patientToken = await login(patientUser, "Payment1234!"); const otherToken = await login(otherUser, "Payment1234!"); const doctorToken = await login(doctorUser, "Payment1234!"); const pack = await Package.findOne({ where: { tenant_id: tenant.id, slug: "monthly-care" } }); const created = await request("/api/v1/payments", { method: "POST", headers: h(patientToken), body: JSON.stringify({ packageId: pack.id, method: "instapay", senderPhone: "01012345678" }) }); const payment = await created.json(); assert.equal(created.status, 201); assert.equal(payment.data.status, "pending"); const receipt = await request(`/api/v1/payments/${payment.data.id}/receipt`, { method: "POST", headers: h(patientToken), body: JSON.stringify({ mimeType: "image/png", originalName: "proof.png", data: Buffer.from([137,80,78,71,13,10,26,10]).toString("base64") }) }); assert.equal(receipt.status, 201); assert.equal((await request(`/api/v1/patient/payments/${payment.data.id}`, { headers: h(otherToken) })).status, 403); assert.equal((await request(`/api/v1/doctor/payments/${payment.data.id}/reject`, { method: "POST", headers: h(doctorToken), body: JSON.stringify({}) })).status, 422); assert.equal((await request(`/api/v1/doctor/payments/${payment.data.id}/reject`, { method: "POST", headers: h(doctorToken), body: JSON.stringify({ reason: "Receipt unclear" }) })).status, 200); assert.equal((await request(`/api/v1/doctor/payments/${payment.data.id}/approve`, { method: "POST", headers: h(doctorToken) })).status, 200); });
  it("prevents patient review and cross-tenant payment access", async (t) => { if (!available) return t.skip(); const token = await login(patientUser, "Payment1234!"); const listed = await request("/api/v1/doctor/payments", { headers: h(token) }); assert.equal(listed.status, 403); });
});
