import { describe, it, before, after } from "node:test";
import assert from "node:assert/strict";
import { createApp } from "../../src/app.js";
import { sequelize } from "../../src/config/database.js";
import { models } from "../../src/models/index.js";
import { hashPassword } from "../../src/utils/auth-crypto.js";
import { notificationService } from "../../src/services/notification.service.js";
const { Tenant, Doctor, Patient, AuthUser, AuthUserTenant, Package } = models;
let server; let base; let available = false; let tenant; let patient; let doctor; let patientUser; let doctorUser;
async function req(path, options = {}) { return fetch(`${base}${path}`, { ...options, headers: { "Content-Type": "application/json", ...(options.headers || {}) } }); }
async function login(user) { const r = await req("/api/v1/auth/login", { method: "POST", body: JSON.stringify({ identifier: user.email, password: "PhaseFive1234!", tenantSlug: tenant.slug }) }); return (await r.json()).data.accessToken; }
function h(t) { return { Authorization: `Bearer ${t}`, "X-Tenant-Slug": tenant.slug }; }
before(async () => { try { await sequelize.authenticate(); available = true; } catch { return; } tenant = await Tenant.findOne({ where: { slug: "dr-kareem" } }); doctor = await Doctor.findOne({ where: { tenant_id: tenant.id, active: true } }); patient = await Patient.create({ tenant_id: tenant.id, full_name: "Phase Five Patient", status: "active" }); patientUser = await AuthUser.create({ email: `phase5-p-${Date.now()}@test.local`, password_hash: await hashPassword("PhaseFive1234!"), user_type: "patient", patient_id: patient.id, status: "enabled" }); doctorUser = await AuthUser.create({ email: `phase5-d-${Date.now()}@test.local`, password_hash: await hashPassword("PhaseFive1234!"), user_type: "doctor", doctor_id: doctor.id, status: "enabled" }); await AuthUserTenant.bulkCreate([{ user_id: patientUser.id, tenant_id: tenant.id, role: "patient", active: true }, { user_id: doctorUser.id, tenant_id: tenant.id, role: "doctor", active: true }]); server = createApp().listen(0); base = `http://localhost:${server.address().port}`; });
after(async () => { if (server) await new Promise((resolve) => server.close(resolve)); await sequelize.close(); });
describe("Phase 5 configuration, notifications, and integration gaps", { concurrency: false }, () => {
  it("allows doctor configuration and denies patient configuration", async (t) => { if (!available) return t.skip(); const doctorToken = await login(doctorUser); const patientToken = await login(patientUser); const pack = await Package.findOne({ where: { tenant_id: tenant.id, slug: "monthly-care" } }); const update = await req(`/api/v1/admin/packages/${pack.id}`, { method: "PATCH", headers: h(doctorToken), body: JSON.stringify({ price: "1250.00", entitlements: [{ code: "weekly_checkin", allowed: true, limitValue: 1, periodUnit: "month" }] }) }); assert.equal(update.status, 200); assert.equal((await req(`/api/v1/admin/packages/${pack.id}`, { method: "PATCH", headers: h(patientToken), body: JSON.stringify({ price: "1" }) })).status, 403); });
  it("isolates notification recipients and supports read state", async (t) => { if (!available) return t.skip(); await notificationService.emit({ tenantId: tenant.id, recipientUserId: patientUser.id, recipientRole: "patient", type: "payment_approved", relatedEntity: "payment", relatedRef: `phase5-${Date.now()}` }); const patientToken = await login(patientUser); const doctorToken = await login(doctorUser); const patientList = await req("/api/v1/notifications?unreadOnly=true", { headers: h(patientToken) }); const doctorList = await req("/api/v1/notifications", { headers: h(doctorToken) }); assert.equal(patientList.status, 200); assert.ok((await patientList.json()).data.length >= 1); assert.equal(doctorList.status, 200); const id = (await req("/api/v1/notifications", { headers: h(patientToken) })).json(); const row = (await id).data[0]; assert.equal((await req(`/api/v1/notifications/${row.id}/read`, { method: "POST", headers: h(patientToken) })).status, 200); assert.equal((await req(`/api/v1/notifications/${row.id}/read`, { method: "POST", headers: h(doctorToken) })).status, 404); });
  it("returns provider-neutral liveSessionId on appointment reads", async (t) => { if (!available) return t.skip(); const patientToken = await login(patientUser); const doctorToken = await login(doctorUser); const created = await req("/api/v1/appointments", { method: "POST", headers: h(patientToken), body: JSON.stringify({ doctorId: doctor.id, type: "online", scheduledStartAt: "2026-09-01T10:00:00.000Z", durationMin: 30 }) }); const appointment = await created.json(); await req(`/api/v1/appointments/${appointment.data.id}/confirm`, { method: "POST", headers: h(doctorToken) }); const live = await req(`/api/v1/appointments/${appointment.data.id}/live-session`, { method: "POST", headers: h(doctorToken) }); const liveBody = await live.json(); const read = await req(`/api/v1/appointments/${appointment.data.id}`, { headers: h(patientToken) }); assert.equal(read.status, 200); assert.equal((await read.json()).data.liveSessionId, String(liveBody.data.id)); });
});
